# Generated by Django 4.2.9 on 2024-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='special_request_info',
            field=models.CharField(blank=True, choices=[('Green Energy', 'Green Energy'), ('Accessibility', 'Accessibility'), ('Luxury', 'Luxury')], max_length=20, null=True),
        ),
    ]
