# Generated by Django 4.2.9 on 2024-02-04 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirm', 'Confirm'), ('Complete', 'Complete')], default='Open', max_length=20)),
                ('can_share', models.BooleanField()),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('special_request_info', models.CharField(blank=True, choices=[('Green Energy', 'Green Energy'), ('Accessibility', 'Accessibility'), ('Luxury', 'Luxury')], max_length=255, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('passenger_num', models.IntegerField(default=1)),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.riderequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='riderequest',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='shared_rides', through='ride.UserRide', to='account.userprofile'),
        ),
    ]
